# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'load.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(728, 593)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.tw_load = QtWidgets.QTableWidget(Form)
        self.tw_load.setObjectName("tw_load")
        self.tw_load.setColumnCount(0)
        self.tw_load.setRowCount(0)
        self.verticalLayout_2.addWidget(self.tw_load)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pb_create_load = QtWidgets.QPushButton(Form)
        self.pb_create_load.setObjectName("pb_create_load")
        self.verticalLayout_3.addWidget(self.pb_create_load)
        self.pb_update_load = QtWidgets.QPushButton(Form)
        self.pb_update_load.setObjectName("pb_update_load")
        self.verticalLayout_3.addWidget(self.pb_update_load)
        self.pb_delete_load = QtWidgets.QPushButton(Form)
        self.pb_delete_load.setObjectName("pb_delete_load")
        self.verticalLayout_3.addWidget(self.pb_delete_load)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.dsb_length = QtWidgets.QDoubleSpinBox(Form)
        self.dsb_length.setObjectName("dsb_length")
        self.verticalLayout_3.addWidget(self.dsb_length)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.dsb_height = QtWidgets.QDoubleSpinBox(Form)
        self.dsb_height.setObjectName("dsb_height")
        self.verticalLayout_3.addWidget(self.dsb_height)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.dsb_width = QtWidgets.QDoubleSpinBox(Form)
        self.dsb_width.setObjectName("dsb_width")
        self.verticalLayout_3.addWidget(self.dsb_width)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.dsb_weight = QtWidgets.QDoubleSpinBox(Form)
        self.dsb_weight.setObjectName("dsb_weight")
        self.verticalLayout_3.addWidget(self.dsb_weight)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.le_load_from = QtWidgets.QLineEdit(Form)
        self.le_load_from.setObjectName("le_load_from")
        self.verticalLayout_3.addWidget(self.le_load_from)
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.le_load_to = QtWidgets.QLineEdit(Form)
        self.le_load_to.setObjectName("le_load_to")
        self.verticalLayout_3.addWidget(self.le_load_to)
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.te_info = QtWidgets.QTextEdit(Form)
        self.te_info.setObjectName("te_info")
        self.verticalLayout_3.addWidget(self.te_info)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_6.setText(_translate("Form", "Список грузов"))
        self.pb_create_load.setText(_translate("Form", "Создать"))
        self.pb_update_load.setText(_translate("Form", "Обновить"))
        self.pb_delete_load.setText(_translate("Form", "Удалить"))
        self.label.setText(_translate("Form", "Длина"))
        self.label_2.setText(_translate("Form", "Высота"))
        self.label_3.setText(_translate("Form", "Ширина"))
        self.label_4.setText(_translate("Form", "Вес"))
        self.label_5.setText(_translate("Form", "Начальный пункт"))
        self.label_7.setText(_translate("Form", "Конечный пункт"))
        self.label_8.setText(_translate("Form", "Дополнительная информация"))
