# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'route.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(728, 593)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.tw_route = QtWidgets.QTableWidget(Form)
        self.tw_route.setObjectName("tw_route")
        self.tw_route.setColumnCount(0)
        self.tw_route.setRowCount(0)
        self.verticalLayout_2.addWidget(self.tw_route)
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.tw_routes = QtWidgets.QTableWidget(Form)
        self.tw_routes.setObjectName("tw_routes")
        self.tw_routes.setColumnCount(0)
        self.tw_routes.setRowCount(0)
        self.verticalLayout_2.addWidget(self.tw_routes)
        self.verticalLayout_2.setStretch(1, 4)
        self.verticalLayout_2.setStretch(3, 1)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pb_create_route = QtWidgets.QPushButton(Form)
        self.pb_create_route.setObjectName("pb_create_route")
        self.verticalLayout_3.addWidget(self.pb_create_route)
        self.pb_update_route = QtWidgets.QPushButton(Form)
        self.pb_update_route.setObjectName("pb_update_route")
        self.verticalLayout_3.addWidget(self.pb_update_route)
        self.pb_delete_route = QtWidgets.QPushButton(Form)
        self.pb_delete_route.setObjectName("pb_delete_route")
        self.verticalLayout_3.addWidget(self.pb_delete_route)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.le_from_warehouse = QtWidgets.QLineEdit(Form)
        self.le_from_warehouse.setObjectName("le_from_warehouse")
        self.verticalLayout_3.addWidget(self.le_from_warehouse)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.le_to_warehouse = QtWidgets.QLineEdit(Form)
        self.le_to_warehouse.setObjectName("le_to_warehouse")
        self.verticalLayout_3.addWidget(self.le_to_warehouse)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.le_person = QtWidgets.QLineEdit(Form)
        self.le_person.setObjectName("le_person")
        self.verticalLayout_3.addWidget(self.le_person)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.le_vehicle = QtWidgets.QLineEdit(Form)
        self.le_vehicle.setObjectName("le_vehicle")
        self.verticalLayout_3.addWidget(self.le_vehicle)
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.le_load = QtWidgets.QLineEdit(Form)
        self.le_load.setObjectName("le_load")
        self.verticalLayout_3.addWidget(self.le_load)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_6.setText(_translate("Form", "Список маршрутов"))
        self.label_9.setText(_translate("Form", "Список маршрутов"))
        self.pb_create_route.setText(_translate("Form", "Создать"))
        self.pb_update_route.setText(_translate("Form", "Обновить"))
        self.pb_delete_route.setText(_translate("Form", "Удалить"))
        self.label.setText(_translate("Form", "Начальный пункт"))
        self.label_2.setText(_translate("Form", "Конечный пункт"))
        self.label_4.setText(_translate("Form", "Водитель"))
        self.label_5.setText(_translate("Form", "Транспортное средство"))
        self.label_7.setText(_translate("Form", "Груз"))
