# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vehicle.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(728, 593)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.tw_vehicle = QtWidgets.QTableWidget(Form)
        self.tw_vehicle.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tw_vehicle.setAlternatingRowColors(True)
        self.tw_vehicle.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tw_vehicle.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tw_vehicle.setColumnCount(4)
        self.tw_vehicle.setObjectName("tw_vehicle")
        self.tw_vehicle.setRowCount(0)
        self.tw_vehicle.horizontalHeader().setVisible(True)
        self.tw_vehicle.verticalHeader().setVisible(True)
        self.verticalLayout_2.addWidget(self.tw_vehicle)
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.tw_routes = QtWidgets.QTableWidget(Form)
        self.tw_routes.setObjectName("tw_routes")
        self.tw_routes.setColumnCount(0)
        self.tw_routes.setRowCount(0)
        self.verticalLayout_2.addWidget(self.tw_routes)
        self.verticalLayout_2.setStretch(1, 4)
        self.verticalLayout_2.setStretch(3, 1)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pb_create_vehicle = QtWidgets.QPushButton(Form)
        self.pb_create_vehicle.setObjectName("pb_create_vehicle")
        self.verticalLayout_3.addWidget(self.pb_create_vehicle)
        self.pb_update_vehicle = QtWidgets.QPushButton(Form)
        self.pb_update_vehicle.setObjectName("pb_update_vehicle")
        self.verticalLayout_3.addWidget(self.pb_update_vehicle)
        self.pb_delete_vehicle = QtWidgets.QPushButton(Form)
        self.pb_delete_vehicle.setObjectName("pb_delete_vehicle")
        self.verticalLayout_3.addWidget(self.pb_delete_vehicle)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.le_model = QtWidgets.QLineEdit(Form)
        self.le_model.setObjectName("le_model")
        self.verticalLayout_3.addWidget(self.le_model)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.le_plate = QtWidgets.QLineEdit(Form)
        self.le_plate.setObjectName("le_plate")
        self.verticalLayout_3.addWidget(self.le_plate)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.le_year = QtWidgets.QLineEdit(Form)
        self.le_year.setObjectName("le_year")
        self.verticalLayout_3.addWidget(self.le_year)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.le_payload = QtWidgets.QLineEdit(Form)
        self.le_payload.setObjectName("le_payload")
        self.verticalLayout_3.addWidget(self.le_payload)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.le_run = QtWidgets.QLineEdit(Form)
        self.le_run.setObjectName("le_run")
        self.verticalLayout_3.addWidget(self.le_run)
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.le_fuel_consumption = QtWidgets.QLineEdit(Form)
        self.le_fuel_consumption.setObjectName("le_fuel_consumption")
        self.verticalLayout_3.addWidget(self.le_fuel_consumption)
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.le_volume = QtWidgets.QLineEdit(Form)
        self.le_volume.setObjectName("le_volume")
        self.verticalLayout_3.addWidget(self.le_volume)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_6.setText(_translate("Form", "Список автомобилей"))
        self.label_9.setText(_translate("Form", "Список маршрутов"))
        self.pb_create_vehicle.setText(_translate("Form", "Создать"))
        self.pb_update_vehicle.setText(_translate("Form", "Обновить"))
        self.pb_delete_vehicle.setText(_translate("Form", "Удалить"))
        self.label.setText(_translate("Form", "Модель"))
        self.label_2.setText(_translate("Form", "Регистрационный номер"))
        self.label_3.setText(_translate("Form", "Год выпуска"))
        self.label_4.setText(_translate("Form", "Грузоподъёмность"))
        self.label_5.setText(_translate("Form", "Пробег"))
        self.label_7.setText(_translate("Form", "Расход топлива"))
        self.label_8.setText(_translate("Form", "Объём кузова"))
